#!/bin/bash

# One of the following: xrandr, acpilight, kernel
METHOD="acpilight"
TEST=$(acpilight -get)
test2=$(echo "scale=0;${TEST}" | bc -l)
test2=${test2%.*}
URGENT_VALUE=9

# Scroll up
if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  if [[ "${test2}" -ge 10 ]]; then #prevents user from turning off screen on accident
    acpilight -dec 5
  fi
#Scroll down
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  acpilight -inc 5
# Left click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  acpilight -dec 1
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  acpilight -inc 1
fi



if [[ "${METHOD}" = "xrandr" ]]; then
  device="${BLOCK_INSTANCE:-primary}"
  xrandrOutput=$(xrandr --verbose)

  if [[ "${device}" = "primary" ]]; then
    device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
  fi

  curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
elif [[ "${METHOD}" = "kernel" ]]; then
  device="${BLOCK_INSTANCE:-intel_backlight}"
  maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
  curBrightness=$(cat /sys/class/backlight/${device}/brightness)
elif [[ "${METHOD}" = "acpilight" ]]; then
  curBrightness=$(acpilight -get)
fi

if [[ "${curBrightness}" -le 0 ]]; then
  exit
fi

if [[ "${METHOD}" = "xrandr" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "kernel" ]]; then
  percent=$(echo "scale=0;${curBrightness} / ${maxBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "acpilight" ]]; then
  percent=$(echo "scale=0;${curBrightness}" | bc -l)
fi

percent=${percent%.*}

if [[ "${percent}" -le 0 ]]; then
  exit
fi

echo "${percent}"
echo "${percent}"
echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
